name = "SBMLToolkit"
uuid = "86080e66-c8ac-44c2-a1a0-9adaadfe4a4e"
authors = ["paulflang", "anandijain"]
version = "0.1.20"

[deps]
Catalyst = "479239e8-5488-4da2-87a7-35f2df7eef83"
MathML = "abcecc63-2b08-419c-80c4-c63dca6fa478"
SBML = "e5567a89-2604-4b09-9718-f5f78e97c3bb"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"

[compat]
Catalyst = "12"
MathML = "0.1"
SBML = "1.4"
SymbolicUtils = "0.17, 0.18, 0.19, 1"
julia = "1.6"

[extras]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SBMLToolkitTestSuite = "792e603a-1588-414c-b272-614011baa40e"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["CSV", "DataFrames", "Downloads", "ModelingToolkit", "OrdinaryDiffEq", "Plots", "SafeTestsets", "SBMLToolkitTestSuite", "Sundials", "Test"]
