name = "SBMLToolkit"
uuid = "86080e66-c8ac-44c2-a1a0-9adaadfe4a4e"
authors = ["paulflang", "anandijain"]
version = "0.1.0"

[deps]
Catalyst = "479239e8-5488-4da2-87a7-35f2df7eef83"
MathML = "abcecc63-2b08-419c-80c4-c63dca6fa478"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
SBML = "e5567a89-2604-4b09-9718-f5f78e97c3bb"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"

[compat]
Catalyst = "6"
MathML = "0.1.7"
ModelingToolkit = "5"
SBML = "0.5.4"
SymbolicUtils = "0.1, 1"
julia = "1.6"

[extras]
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "OrdinaryDiffEq"]
